<a href="https://colab.research.google.com/github/KUGAN123/KUGAN123/blob/main/project_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/product_defects-1.csv")

In [4]:
df.head()

        image_id  pixel_variance  color_deviation  is_defective
0  prod_0000.jpg       46.841947         5.038350             0
1  prod_0001.jpg       49.023405         6.911109             0
2  prod_0002.jpg       32.122725         4.403620             0
3  prod_0003.jpg       54.580532         5.930063             0
4  prod_0004.jpg       59.631456         7.451102             0

In [5]:
df.head(10)

        image_id  pixel_variance  color_deviation  is_defective
0  prod_0000.jpg       46.841947         5.038350             0
1  prod_0001.jpg       49.023405         6.911109             0
2  prod_0002.jpg       32.122725         4.403620             0
3  prod_0003.jpg       54.580532         5.930063             0
4  prod_0004.jpg       59.631456         7.451102             0
5  prod_0005.jpg       50.728020         3.562698             0
6  prod_0006.jpg       49.677461         1.206642             0
7  prod_0007.jpg       35.472826         7.268120             0
8  prod_0008.jpg       38.448384         1.320466             0
9  prod_0009.jpg       37.910504         5.942113             0

from matplotlib import pyplot as plt
_df_0['pixel_variance'].plot(kind='hist', bins=20, title='pixel_variance')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['color_deviation'].plot(kind='hist', bins=20, title='color_deviation')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2.plot(kind='scatter', x='pixel_variance', y='color_deviation', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['is_defective']
  ys = series['pixel_variance']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_3.sort_values('is_defective', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('is_defective')
_ = plt.ylabel('pixel_variance')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['is_defective']
  ys = series['color_deviation']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_4.sort_values('is_defective', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('is_defective')
_ = plt.ylabel('color_deviation')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['is_defective']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'is_defective'}, axis=1)
              .sort_values('is_defective', ascending=True))
  xs = counted['is_defective']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('is_defective', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('is_defective')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_6['pixel_variance'].plot(kind='line', figsize=(8, 4), title='pixel_variance')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_7['color_deviation'].plot(kind='line', figsize=(8, 4), title='color_deviation')
plt.gca().spines[['top', 'right']].set_visible(False)

In [6]:
# prompt: Using dataframe df: pixel_variance between color_deviation	average visualization bar chart

import altair as alt
# Create a bar chart showing the relationship between pixel_variance and color_deviation
chart = alt.Chart(df).mark_bar().encode(
    x='pixel_variance',  # Use pixel_variance for the x-axis
    y='color_deviation'  # Use color_deviation for the y-axis
)
# Display the chart
chart

alt.Chart(...)