<a href="https://colab.research.google.com/github/KUGAN123/KUGAN123/blob/main/project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [20]:
import pandas as pd

In [22]:
df = pd.read_csv("/content/robot_sensors-2.csv")

In [23]:
df.head()

             timestamp  vibration  temperature  motor_current  failure_risk
0  2023-01-01 00:00:00   2.921732    42.891084       2.206488             0
1  2023-01-01 01:00:00   3.750271    65.533347       8.346666             0
2  2023-01-01 02:00:00   4.856672    62.975938       4.026545             0
3  2023-01-01 03:00:00   2.356927    67.014085       2.947543             0
4  2023-01-01 04:00:00   3.155325    73.720153       4.404845             0

In [24]:
df.head(15)

              timestamp  vibration  temperature  motor_current  failure_risk
0   2023-01-01 00:00:00   2.921732    42.891084       2.206488             0
1   2023-01-01 01:00:00   3.750271    65.533347       8.346666             0
2   2023-01-01 02:00:00   4.856672    62.975938       4.026545             0
3   2023-01-01 03:00:00   2.356927    67.014085       2.947543             0
4   2023-01-01 04:00:00   3.155325    73.720153       4.404845             0
5   2023-01-01 05:00:00   1.252930    67.163177       4.840889             0
6   2023-01-01 06:00:00   3.517686    72.406036       5.371944             0
7   2023-01-01 07:00:00   2.578293    84.180976       5.879287             1
8   2023-01-01 08:00:00   2.063876    61.666158       2.847421             0
9   2023-01-01 09:00:00   2.668441    71.732697       4.343674             0
10  2023-01-01 10:00:00   1.573491    71.689218       4.048819             0
11  2023-01-01 11:00:00   1.048967    56.556514       5.839821             0
12  2023-01-01 12:00:00   3.063980    58.879515       4.189715             0
13  2023-01-01 13:00:00   1.361151    80.358697       4.560315             0
14  2023-01-01 14:00:00   1.082314    47.905913       0.449017             0

from matplotlib import pyplot as plt
_df_15['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_16['vibration'].plot(kind='hist', bins=20, title='vibration')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_17['temperature'].plot(kind='hist', bins=20, title='temperature')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_18['motor_current'].plot(kind='hist', bins=20, title='motor_current')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_19.plot(kind='scatter', x='index', y='vibration', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_20.plot(kind='scatter', x='vibration', y='temperature', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_21.plot(kind='scatter', x='temperature', y='motor_current', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_22.plot(kind='scatter', x='motor_current', y='failure_risk', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['vibration']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_23.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('vibration')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['temperature']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_24.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('temperature')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['motor_current']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_25.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('motor_current')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['failure_risk']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_26.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('failure_risk')

from matplotlib import pyplot as plt
_df_27['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_28['vibration'].plot(kind='line', figsize=(8, 4), title='vibration')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_29['temperature'].plot(kind='line', figsize=(8, 4), title='temperature')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_30['motor_current'].plot(kind='line', figsize=(8, 4), title='motor_current')
plt.gca().spines[['top', 'right']].set_visible(False)

In [27]:
# prompt: Using dataframe df: averge of monthly failure

import pandas as pd
# Convert the timestamp column to datetime objects
df['timestamp'] = pd.to_datetime(df['timestamp'])
# Extract the month and year for grouping
df['month'] = df['timestamp'].dt.to_period('M')
# Group by month and calculate the mean of failure_risk
monthly_failure_average = df.groupby('month')['failure_risk'].mean()
# Print the result
monthly_failure_average

month
2023-01    0.084677
2023-02    0.083333
2023-03    0.081989
2023-04    0.076389
2023-05    0.077957
2023-06    0.071736
Freq: M, Name: failure_risk, dtype: float64

In [30]:
# prompt: consumption of motor current

# Filter for rows where motor_current is not NaN
df_motor_current = df.dropna(subset=['motor_current'])
# Group by month and calculate the mean of motor_current
monthly_motor_current_average = df_motor_current.groupby('month')['motor_current'].mean()
# Print the result
monthly_motor_current_average

month
2023-01    4.150039
2023-02    4.267000
2023-03    4.213561
2023-04    4.131563
2023-05    4.162253
2023-06    4.331774
Freq: M, Name: motor_current, dtype: float64